# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1a5286ed899dfdc56653f2801f2c3b7f"
name = "Image Colour Remake"
application_url = "https://image-colour-remake-production.up.railway.app"
embedded = true
handle = "image-colour-remake-2"

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app/subscriptions/update"

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://image-colour-remake-production.up.railway.app/auth/callback",
  "https://image-colour-remake-production.up.railway.app/api/auth/callback"
]

[app_proxy]
url = "https://image-colour-remake-production.up.railway.app/api/storefront-previews"
subpath = "colour-gallery"
prefix = "apps"
