client_id = "1a5286ed899dfdc56653f2801f2c3b7f"
name = "Image Colour Remake"
application_url = "https://image-colour-remake-production.up.railway.app"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://image-colour-remake-production.up.railway.app/auth/callback",
  "https://image-colour-remake-production.up.railway.app/api/auth/callback"
]

[app_proxy]
url = "https://image-colour-remake-production.up.railway.app/api/storefront-previews"
subpath = "colour-gallery"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true